# This file provides instructions for packaging.

`App-perlrdf-Command-Query`
	perl_version_from m`App::perlrdf::Command::Query`;
	version_from      m`App::perlrdf::Command::Query`;
	readme_from       m`App::perlrdf::Command::Query`;
	test_requires     p`Test::More 0.61`  .

