# This file provides instructions for packaging.

`App-perlrdf-Command-Query`
	perl_version_from m`App::perlrdf::Command::Query`;
	version_from      m`App::perlrdf::Command::Query`;
	readme_from       m`App::perlrdf::Command::Query`;
	requires          p`App::perlrdf`;
	requires          p`JSON`;
	requires          p`RDF::Query`;
	requires          p`RDF::Query::Client`;
	requires          p`Spreadsheet::Wright`;
	requires          p`YAML::XS`;
	test_requires     p`Test::More 0.61`.

